export declare var should: any;
import { SearchOptions } from "./search-options";
import { UIElement } from "./ui-element";
export declare function createAppiumDriver(runType: string, port: number, caps: any, isSauceLab?: boolean): AppiumDriver;
export declare class AppiumDriver {
    private _driver;
    private _wd;
    private _runType;
    private _port;
    private caps;
    private _isSauceLab;
    private _capsLocation;
    private static defaultWaitTime;
    private elementHelper;
    private static pngFileExt;
    constructor(_driver: any, _wd: any, _runType: string, _port: number, caps: any, _isSauceLab?: boolean, _capsLocation?: string);
    readonly capabilities: any;
    readonly platformName: any;
    readonly platformVesrion: any;
    readonly driver: any;
    navBack(): Promise<any>;
    findElementByXPath(xPath: string, waitForElement?: number): Promise<UIElement>;
    findElementsByXPath(xPath: string, waitForElement?: number): Promise<UIElement[]>;
    findElementByText(text: string, match?: SearchOptions, waitForElement?: number): Promise<UIElement>;
    findElementsByText(text: string, match?: SearchOptions, waitForElement?: number): Promise<UIElement[]>;
    findElementsByClassName(className: string, waitForElement?: number): Promise<UIElement[]>;
    takeScreenshot(fileName: string): any;
    compareScreen(expected: string, actual: string, output: string): Promise<{}>;
    quit(): Promise<void>;
    private convertArrayToUIElements(array, searchM, args);
}
