export declare var should: any;
import { SearchOptions } from "./search-options";
import { UIElement } from "./ui-element";
import { INsCapabilities } from "./ins-capabilities";
export declare function createAppiumDriver(port: number, args: INsCapabilities): Promise<AppiumDriver>;
export declare class AppiumDriver {
    private _driver;
    private webio;
    private _sessionId;
    private _driverConfig;
    private _args;
    private static defaultWaitTime;
    private elementHelper;
    private static pngFileExt;
    private static partialUrl;
    private _storage;
    constructor(_driver: any, webio: any, _sessionId: any, _driverConfig: any, _args: INsCapabilities);
    readonly capabilities: any;
    readonly platformName: any;
    readonly platformVesrion: any;
    readonly driver: any;
    wdio(): Promise<any>;
    click(args: any): Promise<any>;
    navBack(): Promise<any>;
    findElementByXPath(xPath: string, waitForElement?: number): Promise<UIElement>;
    findElementsByXPath(xPath: string, waitForElement?: number): Promise<UIElement[]>;
    findElementByText(text: string, match?: SearchOptions, waitForElement?: number): Promise<UIElement>;
    findElementsByText(text: string, match?: SearchOptions, waitForElement?: number): Promise<UIElement[]>;
    findElementsByClassName(className: string, waitForElement?: number): Promise<UIElement[]>;
    findElementByAccessibilityId(id: any, waitForElement?: number): Promise<UIElement>;
    findElementsByAccessibilityId(id: string, waitForElement?: number): Promise<UIElement[]>;
    source(): Promise<any>;
    sessionId(): Promise<any>;
    compareScreen(imageName: string, timeOutSeconds: number, tollerance: number): Promise<boolean>;
    takeScreenshot(fileName: string): Promise<string>;
    compareImages(expected: string, actual: string, output: string): Promise<boolean>;
    quit(): Promise<void>;
    private convertArrayToUIElements(array, searchM, args);
}
