export declare var should: any;
import { SearchOptions } from "./search-options";
import { UIElement } from "./ui-element";
export declare function createAppiumDriver(runType: string, port: number, caps: any, isSauceLab?: boolean): Promise<AppiumDriver>;
export declare class AppiumDriver {
    private _driver;
    private webio;
    private _sessionId;
    private _driverConfig;
    private _runType;
    private _port;
    private caps;
    private _isSauceLab;
    private _capsLocation;
    private static defaultWaitTime;
    private elementHelper;
    private static pngFileExt;
    private static partialUrl;
    private _storage;
    constructor(_driver: any, webio: any, _sessionId: any, _driverConfig: any, _runType: string, _port: number, caps: any, _isSauceLab?: boolean, _capsLocation?: string);
    readonly capabilities: any;
    readonly platformName: any;
    readonly platformVesrion: any;
    readonly driver: any;
    wdio(): Promise<any>;
    click(args: any): Promise<any>;
    navBack(): Promise<any>;
    findElementByXPath(xPath: string, waitForElement?: number): Promise<UIElement>;
    findElementsByXPath(xPath: string, waitForElement?: number): Promise<UIElement[]>;
    findElementByText(text: string, match?: SearchOptions, waitForElement?: number): Promise<UIElement>;
    findElementsByText(text: string, match?: SearchOptions, waitForElement?: number): Promise<UIElement[]>;
    findElementsByClassName(className: string, waitForElement?: number): Promise<UIElement[]>;
    waitForElementByAccessibilityId(id: any, waitForElement?: number): Promise<UIElement>;
    waitForElementsByAccessibilityId(id: string, waitForElement?: number): Promise<UIElement[]>;
    source(): Promise<any>;
    sessionId(): Promise<any>;
    compareScreen(imageName: string, timeOutSeconds: number, tollerance: number): Promise<boolean>;
    takeScreenshot(fileName: string): Promise<string>;
    compareImages(expected: string, actual: string, output: string): Promise<boolean>;
    quit(): Promise<void>;
    private convertArrayToUIElements(array, searchM, args);
}
