import { INsCapabilities } from "./ins-capabilities";
export declare function resolve(mainPath: any, ...args: any[]): any;
export declare function fileExists(p: any): boolean;
export declare function isFile(fullName: any): boolean;
export declare function executeNpmInstall(cwd: any): void;
export declare function copy(src: any, dest: any, verbose: any): any;
export declare function contains(source: any, check: any): boolean;
export declare function searchFiles(folder: any, words: any, recursive?: boolean, files?: any[]): Array<string>;
export declare function log(message: any, verbose: any): void;
export declare function loglogOut(line: any, verbose: any): void;
export declare function logErr(line: any, verbose: any): void;
export declare function shutdown(processToKill: any, verbose: any): void;
export declare function killPid(pid: any, verbose: any): void;
export declare function waitForOutput(process: any, matcher: any, errorMatcher: any, timeout: any, verbose: any): Promise<boolean>;
export declare function executeCommand(args: any, cwd?: any): string;
export declare function isWin(): boolean;
export declare function getStorage(args: INsCapabilities): any;
export declare function getReportPath(args: INsCapabilities): any;
export declare function getAppPath(platform: any, runType: any): any;
